title: Piotr Senator
url: "https://senator.lu"
baseurl: ""
markdown: kramdown
theme: minima
permalink: /:categories/:title/
collections:
  trail:
    output: true
  luxembourg:
    output: true
  vienna:
    output: true
  warsaw:
    output: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
